server:
  servlet:
    context-path: /inventory/api
  port: 9091
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:6543/inventory-db'
    username: my_user
    password: my_password
    driverClassName: org.postgresql.Driver